project:
  type: website
  output-dir: docs
  resources:
    - coffee.scss
    - from-coffee-chat-to-r/study-design.R
    - from-coffee-chat-to-r/frequentist.R
    - from-coffee-chat-to-r/effects.R
    
website:
  title: "Coffee and Research"
  site-url: "https://gestimation.github.io/coffee-and-research"
  google-analytics: "G-FCK3LX51C6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "cifmodeling"
        href: https://gestimation.github.io/cifmodeling/
        
      - text: A Conversation on Causality at Our Table (EN)
        menu:
          - text: Index
            href: en/index.qmd
          - text: Study design
            href: en/study-design-1.qmd
      - text: A Conversation on Causality at Our Table (JP)
        menu:
          - text: Index
            href: jp/index.qmd
          - text: Study design
            href: jp/study-design-1.qmd
#          - text: Clinical trial
#            href: jp/clinical-trial-1.qmd
#          - text: Epidemiology
#            href: jp/epidemiology-1.qmd
#          - text: Regression
#            href: jp/logistic-regression-1.qmd
#          - text: Causal inference
#            href: jp/causal-inference-1.qmd
#          - text: Publishing a paper
#            href: jp/publish-a-paper-1.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    page-layout: full