project:
  type: website
  output-dir: docs
  resources:
    - coffee.scss
  
website:
  title: "Coffee and Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "cifmodeling"
        href: https://gestimation.github.io/cifmodeling/
      - text: Story and Quiz (JP)
        menu:
          - text: Study design
            href: jp/study-design-1.md
          - text: Clinical trial
            href: jp/clinical-trial-1.md
          - text: Epidemiology
            href: jp/epidemiology-1.md
          - text: Regression
            href: jp/logistic-regression-1.md
          - text: Causal inference
            href: jp/causal-inference-1.md
          - text: Publishing a paper
            href: jp/publish-a-paper-1.md

format:
  html:
    theme: cosmo
    toc: true
    css: coffee.scss
    page-layout: full